version: '3'
services:
  test_db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: testpw